
spring:
  application:
    name: cloud
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8084/}
  cloud:
    gateway:
      routes:
        - id: first-service
          uri: http://localhost:8085/
          predicates:
            - Path=/first-service/**
          filters:
            - PreGatewayFilter
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8762/eureka

server:
  port: 8084
