spring:
  application:
    name: first-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka # Eureka ??? URL
    register-with-eureka: true  # Eureka ??? ??
    fetch-registry: true        # Eureka ???? ????? ?? ????

server:
  port: 8081