spring:
  application:
    name: second-service
  cloud:
    config:
      enabled: false

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  kafka:
    consumer:
      bootstrap-servers: localhost:9092 # Kafka ???? ?? ?? ??? ??? ??? : ?? ??
      group-id: consumer_group01 # Group Id
      auto-offset-reset: earliest # offset ? ??? ? ?? ?? ?? ??? ???? ?? ??

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka # Eureka ??? URL
    register-with-eureka: true  # Eureka ??? ??
    fetch-registry: true        # Eureka ???? ????? ?? ????

# actuator ??
management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh

server:
  port: 8082

token:
  secret: second