spring:
  application:
    name: store-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/store_db?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect

  zipkin:
    base-url: http://localhost:9411
    enabled: true
  sleuth:
    sampler:
      probability: 1.0

  cloud:
    config:
      enabled: false

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  kafka:
    producer:
      bootstrap-servers: localhost:9092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka # Eureka ??? URL
    register-with-eureka: true  # Eureka ??? ??
    fetch-registry: true        # Eureka ???? ????? ?? ????

# actuator ??
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,beans,httptrace,busrefresh,prometheus,metrics

server:
  port: 8083

token:
  secret: test

topic:
  name: test